print (" ")
print ("~~~~~~~~~~~~~~~~~~~~~")
time.sleep (3)
print ("#                   #")
time.sleep (3)
print ("#    Aldi_fortuna   #")
time.sleep (3)
print ("#        MTK        #")
time.sleep (3)
print ("#                   #")
time.sleep (3)
print ("~~~~~~~~~~~~~~~~~~~~~")
time.slep (3)
print (" ")
print ("===========================================================================")
print (" ")
print ("1. Auto Calcutor")
print ("2. Hitung Bidang")
print (" ")
plh = int(input("Masukan Pilihan Kamu : "))
if plh = 1:
  print ("Diproses...")
  time.sleep (5)
  print (" 25 % ")
