print (" ")
print ("~~~~~~~~~~~~~~~~~~~~~")
print ("#                   #")
print ("#    Aldi_fortuna   #")
print ("#        MTK        #")
print ("#                   #")
print ("~~~~~~~~~~~~~~~~~~~~~")
print (" ")
print ("===========================================================================")
print (" ")
print ("1. Auto Calcutor")
print ("2. Hitung Bidang")
print (" ")
plh = int(input("Masukan Pilihan Kamu : "))
if plh == 1:
  print ("Masukan Bilangan Anda")
  bil1 = input("Masukan Bilangan Pertama : )
